name: check-secrets-action
author: mattdavis0351
description: validation action for this lab

inputs:
  MY_SECRET:
    description: Kuch bhi
    required: true
  secrets-context:
    description: The GitHub Actions secrets context object
    required: true

runs:
  using: node12
  main: "dist/index.js"
